# Generated by Django 5.1.7 on 2025-03-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoPorFaseTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='FaseTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
                ('nroFechaFase', models.CharField(default=' ', max_length=4)),
                ('equipos', models.ManyToManyField(through='base.EquipoPorFaseTorneo', to='base.equipo')),
                ('faseAnterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fasetorneo')),
                ('torneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipoporfasetorneo',
            name='faseTorneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fasetorneo'),
        ),
        migrations.CreateModel(
            name='FechaProde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('apertura', models.DateField()),
                ('cierre', models.DateField()),
                ('concurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.concurso')),
            ],
        ),
        migrations.AddField(
            model_name='concurso',
            name='organizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organizacion'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
                ('puntosObtenidos', models.IntegerField()),
                ('concurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estadio', models.CharField(default=' ', max_length=100)),
                ('resultadoEquipo1', models.SmallIntegerField(null=True)),
                ('resultadoEquipo2', models.SmallIntegerField(null=True)),
                ('resultadoAdicEquipo1', models.SmallIntegerField(null=True)),
                ('resultadoAdicEquipo2', models.SmallIntegerField(null=True)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='base.equipoporfasetorneo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='base.equipoporfasetorneo')),
            ],
        ),
        migrations.CreateModel(
            name='PartidosPorProde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaProde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fechaprode')),
                ('partido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.partido')),
            ],
        ),
        migrations.AddField(
            model_name='fechaprode',
            name='partidos',
            field=models.ManyToManyField(through='base.PartidosPorProde', to='base.partido'),
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadoEquipo1', models.SmallIntegerField(null=True)),
                ('resultadoEquipo2', models.SmallIntegerField(null=True)),
                ('resultadoAdicEquipo1', models.SmallIntegerField(null=True)),
                ('resultadoAdicEquipo2', models.SmallIntegerField(null=True)),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.participante')),
                ('partido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.partidosporprode')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='partidosPorProde',
            field=models.ManyToManyField(through='base.Pronostico', to='base.partidosporprode'),
        ),
    ]
