# Generated by Django 5.1.7 on 2025-03-20 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='deporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.deporte'),
        ),
    ]
