# Generated by Django 5.1.7 on 2025-03-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_torneo_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasetorneo',
            name='nroFechaFase',
        ),
    ]
