# Generated by Django 5.1.7 on 2025-03-21 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_fasetorneo_nrofechafase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin dato', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='equipoporfasetorneo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.categoriaequipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='categorias',
            field=models.ManyToManyField(through='base.EquipoPorFaseTorneo', to='base.categoriaequipo'),
        ),
    ]
