# Generated by Django 5.1.7 on 2025-03-21 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categoriaequipo_equipoporfasetorneo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='equipoporfasetorneo',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fasetorneo',
            name='grupos',
            field=models.ManyToManyField(through='base.EquipoPorFaseTorneo', to='base.grupo'),
        ),
    ]
