# Generated by Django 5.1.7 on 2025-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_grupo_equipoporfasetorneo_grupo_fasetorneo_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='inicio',
            field=models.DateField(null=True),
        ),
    ]
