# Generated by Django 5.1.7 on 2025-03-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_torneo_fin_torneo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
