# Generated by Django 5.1.7 on 2025-03-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_partido_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='organizacion',
        ),
        migrations.CreateModel(
            name='ConcursosOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.concurso')),
                ('organizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organizacion')),
            ],
        ),
        migrations.AddField(
            model_name='organizacion',
            name='concursos',
            field=models.ManyToManyField(through='base.ConcursosOrganizacion', to='base.concurso'),
        ),
    ]
