# Generated by Django 5.1.7 on 2025-03-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_concurso_organizacion_concursosorganizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='concurso',
        ),
        migrations.AddField(
            model_name='participante',
            name='concursoOrganizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.concursosorganizacion'),
        ),
    ]
