# Generated by Django 5.1.7 on 2025-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_participante_concurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
