# Generated by Django 5.1.7 on 2025-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_partido_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
