# Generated by Django 5.1.7 on 2025-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_partido_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default='Sin definir', max_length=50),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultadoAdicEquipo1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultadoAdicEquipo2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultadoEquipo1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultadoEquipo2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='resultadoAdicEquipo1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='resultadoAdicEquipo2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
