# Generated by Django 5.1.7 on 2025-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_grupo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='Ingrese el nombre', max_length=200),
        ),
        migrations.AlterField(
            model_name='fechaprode',
            name='apertura',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fechaprode',
            name='cierre',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='puntosObtenidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
