# Generated by Django 5.1.7 on 2025-04-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_equipo_nombre_alter_fechaprode_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=200, unique=True),
        ),
    ]
