# Generated by Django 5.1.7 on 2025-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_usuario_usuariosporparticipante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='userName',
            field=models.CharField(default='Sin nombre', max_length=200),
        ),
    ]
