# Generated by Django 5.1.7 on 2025-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_usuario_user_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosporparticipante',
            old_name='Participante',
            new_name='participante',
        ),
    ]
