# Generated by Django 5.1.7 on 2025-04-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_participante_usuariosporparticipante_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='userName',
            new_name='nombre',
        ),
    ]
