# Generated by Django 5.1.7 on 2025-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_username_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaprode',
            name='cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
