# Generated by Django 5.1.7 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_partido_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
